@startmindmap
* DSA Pattern
** Array/String
*** Two Pointers
*** Sliding Window
*** Fast & Slow Pointers
** Linked List
*** Fast & Slow Pointers
*** Merge Two Lists
*** Detect Cycle
** Stack
*** Monotonic Stack
*** Next Greater Element
** Queue
*** Sliding Window Maximum
*** BFS Traversal
** Tree
*** DFS Traversal
*** BFS Traversal
*** Binary Search Tree
** Graph
*** DFS Traversal
*** BFS Traversal
*** Topological Sort
** Backtracking
*** Permutations
*** Combinations
*** Subsets
*** Sudoku Solver
** Trie
*** Prefix Tree
*** Suffix Tree
** Heap
*** Min Heap
*** Max Heap
*** Heap Sort
** Hash Table
*** Hash Map
*** Hash Set
** Dynamic Programming
*** Knapsack
*** Longest Common Subsequence
*** Fibonacci Sequence
@endmindmap